package htmlflow

import org.junit.Test
import org.xmlet.htmlapifaster.EnumTypeInputType
import org.xmlet.htmlapifaster.EnumTypeScriptType
import org.xmlet.htmlapifaster.body
import org.xmlet.htmlapifaster.div
import org.xmlet.htmlapifaster.head
import org.xmlet.htmlapifaster.input
import org.xmlet.htmlapifaster.label
import org.xmlet.htmlapifaster.p
import org.xmlet.htmlapifaster.script
import org.xmlet.htmlapifaster.table
import org.xmlet.htmlapifaster.tbody
import org.xmlet.htmlapifaster.td
import org.xmlet.htmlapifaster.tr
import kotlin.test.assertEquals

class DBmonTest {
    @Test
    fun `DBmon of the Datastar Frontend Reactivity`() {
        val out = StringBuilder()
        demoDastarRx.setOut(out).write()
        val expected = expectedDatastarRx.trimIndent().lines().iterator()
        out.toString().split("\n").forEach { actual ->
            assertEquals(expected.next().trim(), actual.trim())
        }
    }

    private val demoDastarRx =
        view<Unit> {
            html {
                head {
                    script {
                        attrType(EnumTypeScriptType.MODULE)
                        attrSrc("https://cdn.jsdelivr.net/gh/starfederation/datastar@1.0.0-RC.5/bundles/datastar.js")
                    }
                }
                body {
                    div {
                        attrId("demo")
                        dataInit("@get('/examples/dbmon/updates')")
                        val editing =
                            dataSignal("editing", false) {
                                ifMissing()
                            }
                        p {
                            +"Average render time for entire page: { renderTime }"
                        }
                        div {
                            addAttr("role", "group")
                            label {
                                +"Mutation Rate %"
                                input {
                                    attrType(EnumTypeInputType.NUMBER)
                                    attrMin("0")
                                    attrMax("100")
                                    attrValue("20")
                                    dataOn("focus", "$editing = true")
                                    dataOn("blur", "@put('/examples/dbmon/inputs'); $editing = false")
                                    val mutationRate = dataBind("mutation-rate")
                                    dataAttr("data-bind-${mutationRate.name}", "$editing")
                                    val mutRate = dataBind("_mutation-rate")
                                    dataAttr("data-bind-${mutRate.name}", "!$editing")
                                }
                            }
                            label {
                                +"FPS"
                                input {
                                    attrType(EnumTypeInputType.NUMBER)
                                    attrMin("1")
                                    attrMax("144")
                                    attrValue("60")
                                    dataOn("focus", "$editing = true")
                                    dataOn("blur", "@put('/examples/dbmon/inputs'); $editing = false")
                                    val framesPerSecond = dataBind("fps")
                                    dataAttr("data-bind-${framesPerSecond.name}", "$editing")
                                    val fps = dataBind("_fps")
                                    dataAttr("data-bind-${fps.name}", "!$editing")
                                }
                            }
                        }
                        table {
                            attrStyle("table-layout: fixed; width: 100%; word-break: break-all")
                            tbody {
                                comment("Dynamic rows generated by server")
                                tr {
                                    td { +"cluster1" }
                                    td {
                                        attrStyle("background-color: var(--_active-color)")
                                        attrClass("success")
                                        +"8"
                                    }
                                    td {
                                        addAttr("aria-description", "SELECT blah from something")
                                        +"12ms"
                                    }
                                    comment("More query cells...")
                                }
                                comment("More database rows...")
                            }
                        }
                    }
                }
            }
        }

    private val expectedDatastarRx =
        """
        <!DOCTYPE html>
        <html>
            <head>
                <script type="module" src="https://cdn.jsdelivr.net/gh/starfederation/datastar@1.0.0-RC.5/bundles/datastar.js">
                </script>
            </head>
            <body>
                <div id="demo" data-init="@get('/examples/dbmon/updates')" data-signals-editing__ifmissing="false">
                    <p>
                        Average render time for entire page: { renderTime }
                    </p>
                    <div role="group">
                        <label>
                            Mutation Rate %
                            <input type="number" min="0" max="100" value="20" data-on-focus="${'$'}editing = true" data-on-blur="@put('/examples/dbmon/inputs'); ${'$'}editing = false" data-bind-mutation-rate="" data-attr:data-bind-mutation-rate="${'$'}editing" data-bind-_mutation-rate="" data-attr:data-bind-_mutation-rate="!${'$'}editing">
                        </label>
                        <label>
                            FPS
                            <input type="number" min="1" max="144" value="60" data-on-focus="${'$'}editing = true" data-on-blur="@put('/examples/dbmon/inputs'); ${'$'}editing = false" data-bind-fps="" data-attr:data-bind-fps="${'$'}editing" data-bind-_fps="" data-attr:data-bind-_fps="!${'$'}editing">
                        </label>
                    </div>
                    <table style="table-layout: fixed; width: 100%; word-break: break-all">
                        <tbody>
                            <!-- Dynamic rows generated by server -->
                            <tr>
                                <td>
                                    cluster1
                                </td>
                                <td style="background-color: var(--_active-color)" class="success">
                                    8
                                </td>
                                <td aria-description="SELECT blah from something">
                                    12ms
                                </td>
                                <!-- More query cells... -->
                            </tr>
                            <!-- More database rows... -->
                        </tbody>
                    </table>
                </div>
            </body>
        </html>    
        """.trimIndent()
}
