/**
 * Core client-side engine for the MFE library.
 *
 * Defines the `<micro-frontend>` custom element (backed by the {@link Mfe} class), which
 * fetches and renders an HTML fragment (or streamed HTML fragments) from a configured URL
 * into its own shadow root, adopts shared/own CSS stylesheets, and exposes a small pub-sub
 * API (`window.mfe(name, callback)` / the `MfeContext` handed to that callback) so host-page
 * scripts can react to a fragment becoming ready, trigger/listen for custom cross-fragment
 * events, and force a reload.
 *
 * See `docs/MFE-API.md` for the full consumer-facing API reference.
 */
import { loadStylesheet, adoptStylesheet } from "./theme-loader.js";
import { createSafeHtml } from "./html-sanitizer.js";

/**
 * The object passed to every `onInit`/`mfe()` callback once a `<micro-frontend>` fragment is
 * ready. Gives access to the fragment's shadow root and a small
 * cross-fragment communication API built on top of the shared {@link Mfe.mfeEventBus}.
 */
interface MfeContext {
    root: ShadowRoot | null;
    /**
     * Dispatches a custom event on the shared MFE event bus.
     * @param message - free-form string payload (e.g. a short description of the event).
     * @param payload - arbitrary structured data attached to the event's `detail.payload`.
     * @param eventName - event name to dispatch; falls back to this fragment's configured
     *                     `mfe-trigger-event` attribute value if omitted/falsy.
     */
    triggerMfeEvent: (message: string, payload: unknown, eventName: string, ) => void;
    /**
     * Registers a listener on the shared MFE event bus. The listener is tracked and
     * automatically removed the next time this fragment reloads, to avoid leaking
     * listeners/duplicate registrations across reloads.
     * @param listener - standard DOM `EventListener` invoked when the event fires.
     * @param eventName - event name to listen for; falls back to this fragment's configured
     *                     `mfe-listen-event` attribute value if omitted/falsy.
     */
    listenMfeEvent: (listener: EventListener, eventName: string) => void;
    /** Forces this fragment to re-fetch and re-render its content immediately. */
    reloadMfe: () => void;
    /** Re-exports {@link MfcEventType} for convenience so consumers don't need a separate import. */
    mfeEvents: typeof MfcEventType
}

declare global {
    interface Window {
        /**
         * Global entry point for host-page scripts to register a callback that runs once the
         * named `<micro-frontend>` fragment has finished loading (or immediately, if it's
         * already ready). Equivalent to calling {@link Mfe.onReady} directly.
         */
        mfe: (name: string, callback: (mfeContext: MfeContext) => void) => void;
    }
}

/** Event types dispatched internally to control fragment reload behavior. */
enum MfcEventType {
    RELOAD = "RELOAD"
}

/**
 * Custom event type dispatched on the shared MFE event bus to trigger a fragment reload.
 * Encapsulates the "reload" event name and its typed `detail` payload in one place, so
 * dispatch/handling sites don't need to manually construct/inspect the `detail` shape.
 */
class MfeReloadEvent extends CustomEvent<{ type: MfcEventType }> {
    constructor(type: MfcEventType = MfcEventType.RELOAD) {
        super("reload", { detail: { type } });
    }
}

/**
 * Custom element implementation backing `<micro-frontend>` elements generated by the HtmlFlow library.
 *
 * Configuration is entirely attribute-driven (read once in {@link connectedCallback} via
 * {@link collectMfeAttributes}): `mfe-url` (required, the fragment source), `mfe-name`
 * (required, used as key in the static {@link registry} and for ready-event naming),
 * `mfe-styling-url` / `mfe-shared-styling-url` (optional styling to adopt into fragments shadow root, 
 *  the shared one is auto-propagated onto `document` when used),
 * `mfe-listen-event` / `mfe-trigger-event` (optional cross-fragment event names), and
 * `mfe-stream-data` (`"true"` switches from a single buffered fetch/render via
 * {@link buildFragment} to incremental chunked rendering via {@link fetchStreamData}).
 */
class Mfe extends HTMLElement {
    private mfeReady: boolean = false;
    private mfeName: string | null = "";
    private mfeUrlResource: string | null = "";
    private mfeListeningEventName: string | null = "";
    private mfeTriggerEventName: string | null = "";
    /** Suffix appended to `mfeName` to form the "fragment ready" event name on the event bus. */
    private readonly readyEventSuffix: string = "-fragment-ready";
    private mfeStylingUrl: string | null = "";
    private mfeSharedStylingUrl: string | null = "";
    private isMfeStreamingData: string | null = "";
    /** Aborts any in-flight non-streaming fetch when a new load/reload starts. */
    private abortController: AbortController | null = null;
    /** Bound once so the same function reference can be added/removed as an event listener. */
    private bindReload = this.reloadFragment.bind(this); // prevent new reference
    /** Maps `mfeName` -> live instance, so {@link onReady} can look up an already-connected fragment. */
    private static registry = new Map<string, Mfe>();
    /** Buffers `onReady` callbacks registered before their target fragment has connected/registered itself. */
    private static pendingCallBacks = new Map<string, ((mfeRoot: MfeContext)=>void)[]>();
    /** Single event bus shared by every `<micro-frontend>` instance on the page. */
    private static mfeEventBus = new EventTarget();

    /** Listeners registered via {@link createContext}'s `listenMfeEvent`, tracked for cleanup on reload/disconnect. */
    private windowListeners: { eventName: string; handler: EventListener }[] = [];

    /** Removes every listener registered through this fragment's `MfeContext`, then clears the tracking list. */
    private cleanupWindowListeners() {
        this.windowListeners.forEach(({ eventName, handler }) => {
            Mfe.mfeEventBus.removeEventListener(eventName, handler);
        });
        this.windowListeners = [];
    }

    constructor() {
        super();
        this.attachShadow({ mode: 'open' });
    }

    /**
     * Standard custom element lifecycle hook. Reads configuration attributes, wires up the
     * reload listener, validates required attributes, registers this instance so
     * {@link onReady} can find it, flushes any callbacks that were queued before this fragment
     * connected, and kicks off the initial fragment load.
     */
    connectedCallback() {
        this.collectMfeAttributes();
        if (this.mfeListeningEventName) {
            console.log(this.mfeListeningEventName);
            Mfe.mfeEventBus.addEventListener(this.mfeListeningEventName, this.bindReload);
        }

        if(!this.mfeUrlResource){
            console.error(`MFE -> ${this.mfeName} is missing the "mfe-url" attribute.`);
             return;
        }
        if(!this.mfeName) {
            console.error(`MFE -> ${this.mfeName} is missing the "mfe-name" attribute. The ready event will be dispatched with an undefined name.`);
            return;
        }
        if(!this.mfeTriggerEventName) {
            console.error(`MFE -> ${this.mfeName} is missing the "mfe-trigger-event" attribute. The fragment will not be able to trigger any custom events.`);
        }
        if(!this.mfeListeningEventName) {
            console.error(`MFE -> ${this.mfeName} is missing the "mfe-listen-event" attribute. The fragment will not reload on any event.`);
        }
        if(!this.mfeStylingUrl) {
            console.warn(`MFE -> ${this.mfeName} is missing the "mfe-styling-url" attribute. The fragment will not fetch any custom styling.`);
        }
        this.shadowRoot?.appendChild(document.createTextNode(`Loading ${this.mfeName}...`));
        Mfe.registry.set(this.mfeName, this);
        Mfe.pendingCallBacks.get(this.mfeName)?.forEach(cb => this.onInit(cb))
        Mfe.pendingCallBacks.delete(this.mfeName);

        this.loadFragment();
    }


    /** Reads and stores all `mfe-*` configuration attributes from the host element. */
    private collectMfeAttributes() {
        this.mfeUrlResource = this.getAttribute("mfe-url");
        this.mfeName = this.getAttribute("mfe-name");
        this.mfeStylingUrl = this.getAttribute("mfe-styling-url");
        this.mfeSharedStylingUrl = this.getAttribute("mfe-shared-styling-url");
        this.mfeListeningEventName = this.getAttribute("mfe-listen-event");
        this.mfeTriggerEventName = this.getAttribute("mfe-trigger-event");
        this.isMfeStreamingData = this.getAttribute("mfe-stream-data");
    }

    /**
     * Registers a callback to run once this fragment is ready. If it's already ready, the
     * callback runs synchronously with the current context; otherwise it's deferred until the
     * fragment's "ready" event fires on the shared event bus (at which point any listeners
     * registered through a previous context are also cleaned up, since a new context will be
     * created for this callback).
     */
    public onInit(callBackFn: (shadowRoot: MfeContext) => void): void {
        if(this.mfeReady && this.shadowRoot){
            callBackFn(this.createContext(this.shadowRoot));
        }
        else Mfe.mfeEventBus.addEventListener(this.mfeName + this.readyEventSuffix, () => {
            this.cleanupWindowListeners();
            callBackFn(this.createContext(this.shadowRoot))
        });
    };

    /** Builds the {@link MfeContext} object handed to `onInit`/`mfe()` callbacks for this fragment. */
    private createContext(root: ShadowRoot | null): MfeContext {
        return {
            root,
            triggerMfeEvent: (message: string, payload: unknown, eventName: string) => this.triggerEvent(eventName ?? this.mfeTriggerEventName, message, payload),
            listenMfeEvent: (listener, eventName) => {
                const evName = eventName ?? this.mfeListeningEventName;
                Mfe.mfeEventBus.addEventListener(evName, listener);
                this.windowListeners.push({eventName: evName, handler: listener});
            },
            reloadMfe: () => this.reloadFragment(new MfeReloadEvent()),
            mfeEvents: MfcEventType
        }
    }

    /**
     * Looks up the named fragment and invokes `onInit` on it if it has already connected;
     * otherwise queues the callback in {@link pendingCallBacks} until a fragment with that
     * name connects and drains the queue (see {@link connectedCallback}).
     */
    public static onReady(mfeName: string, cbFn:(mfeCtx: MfeContext) => void): void {
        const mfeInstance = Mfe.registry.get(mfeName);
        if(mfeInstance){
           mfeInstance.onInit(cbFn);
        }else{
            const queue = Mfe.pendingCallBacks.get(mfeName) ?? [];
            queue.push(cbFn);
            Mfe.pendingCallBacks.set(mfeName, queue);
        }
    }

    /**
     * Fetches this fragment's full HTML in one buffered request, used by
     * {@link loadFragment} when `mfe-stream-data` is not `"true"`. Aborts any previous in-flight
     * fetch first, so overlapping requests do not create race conditions.
     * @returns the response body text, or undefined if no `mfe-url` is configured.
     */
    private async fetchData() {
        this.abortController?.abort();
        this.abortController = new AbortController();
        if(this.mfeUrlResource){
            const response = await fetch(this.mfeUrlResource, {
                signal: this.abortController.signal,
            });
            if (!response.ok) {
                throw new Error(`Failed to fetch ${this.mfeUrlResource}: ${response.status}`);
            }
            return response.text();
        }
    }

    /**
     * Fetches and incrementally renders this fragment's HTML as it streams in, used by
     * {@link loadFragment} when `mfe-stream-data` is `"true"`. Clears any previous content,
     * adopts stylesheets up front, then for each decoded chunk: the first chunk containing a
     * slot element defined is treated as the container markup and appended directly to the shadow
     * root. It must include any `<slot name="x">` placeholders the later chunks target,
     * subsequent chunks carrying a `slot="x"` attribute are appended as that slot's fallback
     * content (looked up via `slot[name="x"]`) rather than via native slot *assignment*, since
     * nothing is placed in light DOM. Any other chunk is appended directly to the shadow root.
     */
    private async fetchStreamData() {
        const decoder = new TextDecoder();
        if(this.shadowRoot){
            this.shadowRoot.replaceChildren();
        }
        this.adoptStyleSheets();
        if(this.mfeUrlResource){
            const response = await fetch(this.mfeUrlResource);
            if (!response.ok) {
                throw new Error(`[micro-frontend "${this.mfeName}"] fetch failed: ${response.status}`);
            }
            if(response.body){
                for await (const value of response.body as any) {
                const chunk = decoder.decode(new Uint8Array(value), {stream: true});
                const node = createSafeHtml(chunk);
                if (node.content.querySelector('slot')) {
                    this.shadowRoot?.append(node.content);
                    continue;
                }else{
                    console.error("No <slot> elements were found in the wrapper, content wont be rendered correctly.");
                }
                const slotted = node.content.querySelector('[slot]');
                if (slotted) {
                    const slotName = slotted.getAttribute('slot');
                    this.shadowRoot?.querySelector(`slot[name="${slotName}"]`)?.append(node.content);
                } else {
                    this.shadowRoot?.append(node.content);
                }
            }
            }
        }
    }


    /**
     * Loads this fragment's configured
     * stylesheets, then assigns them to the shadow root's `adoptedStyleSheets`. Both URLs are
     * fetched/parsed concurrently via {@link loadStylesheet} promise cache; failures on either URL are
     * caught and logged, resolving to `null` so one broken stylesheet doesn't block the other.
     * The shared stylesheet is also adopted onto `document.adoptedStyleSheets` (via
     * {@link adoptStylesheet}) so the host shell picks up the same theme.
     */
    private adoptStyleSheets(): void {
        if (!this.mfeSharedStylingUrl && !this.mfeStylingUrl) {
            return;
        }

        const safeLoadStylesheet = (url: string | null, label: string) => url ? loadStylesheet(url).catch(err => { console.error(`Failed to load ${label}`, err); return null; }) : Promise.resolve(null);

        const sharedSheet$ = safeLoadStylesheet(this.mfeSharedStylingUrl, 'shared stylesheet')
        const ownSheet$ = safeLoadStylesheet(this.mfeStylingUrl, `stylesheet for MFE -> ${this.mfeName}`)

        if (this.mfeSharedStylingUrl) {
            adoptStylesheet(document, this.mfeSharedStylingUrl).catch(err =>
                console.error(`Failed to adopt shared theme onto document for MFE -> ${this.mfeName}`, err));
        }

        Promise.all([sharedSheet$, ownSheet$]).then(([sharedSheet, ownSheet]) => {
            if (this.shadowRoot) {
                this.shadowRoot.adoptedStyleSheets = [sharedSheet, ownSheet].filter((sheet): sheet is CSSStyleSheet => sheet !== null);
            }
        })
    }

    /**
     * Renders a fully-buffered HTML string into the shadow root: clears
     * any previous content, sanitizes the HTML via {@link createSafeHtml}, adopts stylesheets,
     * then appends the sanitized fragment.
     */
    private buildFragment(html: string) {
        if(this.shadowRoot){
            this.shadowRoot.replaceChildren();
        }
        const fragment = createSafeHtml(html);
        this.adoptStyleSheets();
        this.shadowRoot?.append(fragment.content);
    }

    /**
     * Dispatches a custom event on the shared MFE event bus, carrying `message`/`payload` in
     * `detail`. Used both internally (e.g. reload signaling) and via {@link MfeContext.triggerMfeEvent}.
     */
    public triggerEvent(
        eventName: string,
        message: string,
        payload: unknown
    ): void {
        const event = new CustomEvent(eventName, {
            detail: { message, payload }
        });
        Mfe.mfeEventBus.dispatchEvent(event);
    }

    /**
     * Event bus handler bound to `mfe-listen-event`; re-triggers {@link loadFragment} when the
     * received event is an {@link MfeReloadEvent} whose `detail.type` is {@link MfcEventType.RELOAD}
     */
    private reloadFragment(event:Event){
        if(event instanceof MfeReloadEvent){
            this.mfeReady = false;
            if(event.detail.type === MfcEventType.RELOAD){
                this.loadFragment();
            }
        }
    }

    /**
     * Dispatches to either {@link fetchStreamData} or {@link fetchData} + {@link buildFragment}
     * and emits the "fragment ready" event once rendering completes.
     */
    private loadFragment() {
        if(this.isMfeStreamingData === "true"){
            this.fetchStreamData().then(r => this.emitFragmentReadiness()).catch(err => {
                this.shadowRoot?.appendChild(document.createTextNode(`Failed to fetch: ${this.mfeName}`));
                console.error(`An error occured for MFE -> ${this.mfeName}`, err)
            });
        }
        else{
            this.fetchData().then(r => {
                if(r){
                    this.buildFragment(r);
                    this.emitFragmentReadiness();
                }
            }).catch(err => {
                this.shadowRoot?.appendChild(document.createTextNode(`Failed to fetch: ${this.mfeName}`));
                console.error(`An error occured for MFE -> ${this.mfeName}`, err)
            });
        }
    }

    /** Marks this fragment ready and dispatches its "fragment ready" event on the shared bus, triggering any pending `onInit`/`onReady` callbacks. */
    private emitFragmentReadiness() {
        this.mfeReady = true;
        console.info(`Dispatching ${this.mfeName}${this.readyEventSuffix} event!`);
        Mfe.mfeEventBus.dispatchEvent(new Event(this.mfeName + this.readyEventSuffix));
    }

    /** Standard custom element lifecycle hook: cleans up event listeners and aborts any in-flight fetch when this fragment is removed from the page. */
    disconnectedCallback() {
        this.cleanupWindowListeners();
        console.log(`MFE -> ${this.mfeName} removed from page.`);
        if(this.mfeListeningEventName) Mfe.mfeEventBus.removeEventListener(this.mfeListeningEventName, this.bindReload);
        this.abortController?.abort();
    }

    adoptedCallback() {
        console.log(`MFE -> ${this.mfeName} moved to new page.`);
    }

    /**
     * Instance-level alias for {@link onReady}, allowing a fragment reference to be obtained
     * through element query selection to still.
     */
    public mfe(name:string, callback: (mfeContext: MfeContext) => void) {
        Mfe.onReady(name, callback);
    }

}

// Registers the custom element and exposes the `window.mfe(...)` global entry point
window.customElements.define('micro-frontend', Mfe);
window.mfe = (name, callbackFn) => Mfe.onReady(name, callbackFn);
export default Mfe;
