/*
 * MIT License
 *
 * Copyright (c) 2025, xmlet HtmlFlow
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package htmlflow.continuations;

import htmlflow.visitor.HtmlVisitor;
import htmlflow.visitor.Tags;
import htmlflow.visitor.escape.HtmlEscapers;
import java.util.function.Function;
import java.util.function.Predicate;
import java.util.function.ToDoubleFunction;
import java.util.function.ToIntFunction;
import java.util.function.ToLongFunction;

/**
 * HtmlContinuation for a single value read from the model. The markup around the value stays in
 * the neighbor static HTML blocks, which are preencoded.
 *
 * @author Bernardo Pereira
 */
public class HtmlContinuationSyncValue extends HtmlContinuationSync {

    public enum Kind {
        /** The value as it is, without escaping. */
        RAW,
        /** The value with HTML escaping. */
        TEXT,
        INT,
        LONG,
        DOUBLE,
        BOOLEAN,
        /** An attribute that we only write when the accessor does not return null. */
        ATTR_NULLABLE,
    }

    private final Kind kind;
    private final Object accessor;

    /** The name of the attribute, which we only use for the Kind ATTR_NULLABLE. */
    private final String attributeName;

    /**
     * Sets indentation to -1 to inform that visitor should continue with previous indentation.
     * A value slot changes neither the depth nor the isClosed of the visitor.
     */
    public HtmlContinuationSyncValue(
        Kind kind,
        Object accessor,
        String attributeName,
        HtmlVisitor visitor,
        HtmlContinuation next
    ) {
        super(-1, false, visitor, next);
        this.kind = kind;
        this.accessor = accessor;
        this.attributeName = attributeName;
    }

    public Kind kind() {
        return kind;
    }

    public Object accessor() {
        return accessor;
    }

    public String attributeName() {
        return attributeName;
    }

    /**
     * Escapes the value of a textOf slot.
     *
     * @apiNote The generated bytecode invokes this method by its name, so renaming it makes
     *     every compiled chain fall back to the linked one.
     */
    public static String text(Object value) {
        return HtmlEscapers.htmlEscaper().escape(String.valueOf(value));
    }

    /**
     * Writes an attribute of an attrOfNullable slot, only when the value is not null.
     *
     * @apiNote The generated bytecode invokes this method by its name, as in {@link #text}.
     */
    public static void attrNullable(
        HtmlVisitor visitor,
        String name,
        Object value
    ) {
        if (value != null) Tags.addAttribute(
            visitor.out(),
            name,
            String.valueOf(value)
        );
    }

    @SuppressWarnings("unchecked")
    @Override
    protected final void emitHtml(Object model) {
        if (kind == Kind.ATTR_NULLABLE) {
            attrNullable(
                visitor,
                attributeName,
                ((Function<Object, ?>) accessor).apply(model)
            );
        } else {
            visitor.write(rendered(model));
        }
    }

    @SuppressWarnings("unchecked")
    private String rendered(Object model) {
        switch (kind) {
            case INT:
                return Integer.toString(
                    ((ToIntFunction<Object>) accessor).applyAsInt(model)
                );
            case LONG:
                return Long.toString(
                    ((ToLongFunction<Object>) accessor).applyAsLong(model)
                );
            case DOUBLE:
                return Double.toString(
                    ((ToDoubleFunction<Object>) accessor).applyAsDouble(model)
                );
            case BOOLEAN:
                return Boolean.toString(
                    ((Predicate<Object>) accessor).test(model)
                );
            case TEXT:
                return text(((Function<Object, ?>) accessor).apply(model));
            default:
                return String.valueOf(
                    ((Function<Object, ?>) accessor).apply(model)
                );
        }
    }

    @Override
    public HtmlContinuation copy(HtmlVisitor v) {
        return new HtmlContinuationSyncValue(
            kind,
            accessor,
            attributeName,
            v,
            next != null ? next.copy(v) : null
        );
    }
}
